document.write("<h3> Rules for naming JS variables </h3>")
document.write("<br>")
document.write("a) variable name can only contain numbers , letters , underscore & dash")
document.write("<br>")
document.write("b) variable name can only start with $ , letters , & _")
document.write("<br>")
document.write("c) variable names are case sensitive")
document.write("<br>")
document.write("b) variable name can cot contain JS keywords")